### ISSUE TITLE
[Latest] 2.3.161 Failure to Launch

### ISSUE THREAD

**Issue by TechnoColt** [p455w0rd/p455w0rds-Library#66]
Hey there, p455w0rd,

I've been having some issues with DankNull, so I updated to the latest I could find, 1.7.89, which required me to update your library to 2.3.161. Unfortunately, upon launch, I encountered a java.lang.NoSuchMethodError. The full crash report is in the following pastebin.

https://pastebin.com/BJBr1Rje

**Comment by Spitfire2k6** [comment]
exact same issue.
https://pastebin.com/QME4fFTp

**Comment by as-nick** [comment]
Same issue here, any news? My DankNull hotkeys aren't working in v1.6.80 and if I want to update it, I need to update your lib, which is causing these issues.

**Comment by cjm721** [comment]
Issue is with https://github.com/p455w0rd/AE2WirelessTerminalLibrary not this library.
